name: CI

on:
  push:
    branches: [main,develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installer uv
        run: pip install uv

      - name: Installer ruff
        run: uv pip install ruff
      
      - name: Installer les dépendances
        run: uv sync

      - name: Exécuter ruff check
        run: uv run ruff check .

      - name: Vérifier le formatage
        run: uv run ruff format --check

  typecheck:
    name: Vérification des types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installer uv
        run: pip install uv

      - name: Installer mypy
        run: uv pip install mypy
      
      - name: Installer les dépendances
        run: uv sync

      - name: Exécuter mypy
        run: uv run mypy app/

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installer uv
        run: pip install uv

      - name: Installer Bandit
        run: uv pip install bandit
      
      - name: Installer Safety
        run: uv pip install safety

      - name: Installer les dépendances
        run: uv sync

      - name: Bandit (static analysis)
        run: uv run bandit -r app/

      - name: Safety (check dependencies vulnerabilities)
        run: uv run safety check
  
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installer uv
        run: pip install uv

      - name: installation de pytest
        run: uv pip install pytest

      - name: installation des dépendances
        run: uv sync

      - name: run pytest
        run: uv run pytest --cov=app --cov-report=term --cov-report=xml


